### ISSUE TITLE
Items

### ISSUE THREAD

**Issue by calclavia** [NOVAAPI/NovaSuggestions#14]
How do we deal with items? Items are to be Stateful. Does that mean the item doesn't need reference to its itemStack anymore?

**Comment by asiekierka** [comment]
It doesn't.

Not all Items are Stateful; what decides of Statefulness of an Item is whether it implements Storable *only*. The ItemStack is merely an instance of an Item (or the same instance if it's not Storable) combined with a stack size number and utility functions for managing the stack size, comparing stacks, adding stacks together, et cetera.

**Comment by calclavia** [comment]
Got it.
