### ISSUE TITLE
Unified tick time

### ISSUE THREAD

**Issue by Alex-hawks** [NOVAAPI/NovaSuggestions#19]
There might be games out there that have a tick rate that isn't 20 ticks per second. How do you intend to deal with that? Expose the expected tick rate based on the environment to the mods? If it was done that way, Minecraft would always be 20 ticks per second according to the "Constant"

**Comment by magik6k** [comment]
There is at least one game that doesn't define ticking, where entities declare when they want to get tickec, so a furnace can tell engine to be ticked once after some time after putting some smeltable item

**Comment by asiekierka** [comment]
Our plan was to have Updatable give the delta time, that is a double stating the time in seconds that passed since the last tick; and then add something like a getMinimumDeltaTime()

**Comment by Alex-hawks** [comment]
So like updateEntity in tile entities, but instead of knowing like in Minecraft, it is told how long since it last ticked?

**Comment by calclavia** [comment]
@Alex-hawks notice how UpdateTicker can be threaded and has a variable tick rate. Also, notice how Updater has a deltaTime update parameter.
