### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by shadowfacts** [NOVAAPI/NovaSuggestions#20]
Both for mods and for Nova itself. Would be something similar to [this](https://github.com/MinecraftForge/MinecraftForge/blob/master/src/main/java/net/minecraftforge/common/config/Configuration.java).

**Comment by Kubuxu** [comment]
We have planned using https://github.com/typesafehub/config. It has nice clean API, is checked and has nice parser.

**Comment by shadowfacts** [comment]
Nice, typesafe's config library look pretty good.
