### ISSUE TITLE
Native feature support.

### ISSUE THREAD

**Issue by gjgfuj** [NOVAAPI/NovaSuggestions#22]
Some way to integrate with native systems that weren't designed for nova but were instead designed for native. I.e. the RF api for minecraft.

Suggestions include:
1. Allow for determining the game and the specific wrapper, and then allow for the nova mod to design content specifically for the game. I.e. allow a custom tile entity for minecraft for example.

2. Use ASM/Some other hack to allow injection of native APIs ported to NOVA w/ backwards and forwards conversions that are non-standard as part of the game.

I would personally prefer the second, but it would require additional integration issues and requiring a port to be included as part of the mod.

**Comment by calclavia** [comment]
I've already got code for this in my ASM library. I'll be doing pass-through injections. This code will also be the basis of microblock systems based on Forge Multiparts.

**Comment by gjgfuj** [comment]
Is this usable for any generic API from native if that's usable? And vice versa?

**Comment by calclavia** [comment]
Yup. ASM will basically generate a new class, with the mixed interfaces in.

**Comment by asiekierka** [comment]
Two plans we had:

1. Passthrough interfaces
2. Some common APIs will simply be implemented in a nova.platform.minecraft package, or linked to our existing APIs where possible.

**Comment by gjgfuj** [comment]
That sounds great!

**Comment by calclavia** [comment]
Duplicate https://github.com/NOVAAPI/NovaSuggestions/issues/11
