### ISSUE TITLE
Block Registration

### ISSUE THREAD

**Issue by calclavia** [NOVAAPI/NovaSuggestions#6]
I've been thinking. How should we register blocks? Should we register the Class of the block and have paramters injected via reflection? Registering a Block object doesn't make sense anymore as it requires Vector and BlockAccess.

**Comment by Alex-hawks** [comment]
Register a name to class relationship, with an optional factory instance for creating instances of the block. If the factory is not specified, then call the default no-args constructor on the block for creation.

**Comment by calclavia** [comment]
Should close this issue. Already complete. Also, nice to see you again @Alex-hawks
